server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/camunda
    username: camunda
    password: camunda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstname: Demo
    database:
      type: postgres
    job-execution:
      enabled: true
    history-level: full
    webapp:
      application-path: /camunda

logging:
  level:
    org.camunda.bpm.engine: INFO